env:
  node: true

extends:
  - airbnb-base
  - plugin:prettier/recommended
  - prettier

plugins:
  - prettier
  - unicorn

overrides:
  - files:
      - "**/*.ts"
      - "**/*.tsx"

    env:
      browser: true
      es6: true
      jest: true

    parser: "@typescript-eslint/parser"

    parserOptions:
      # TypeScript
      project: tsconfig.json

      # Modern JavaScript
      ecmaVersion: 2018
      sourceType: module

      # React
      ecmaFeatures:
        jsx: true

    extends:
      # JavaScript and React
      - airbnb
      - airbnb/hooks
      - plugin:unicorn/recommended

      # Jest-dom
      - plugin:jest-dom/recommended

      # TypeScript
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended

      # Prettier
      - plugin:prettier/recommended
      - prettier
      - prettier/react
      - prettier/@typescript-eslint

    plugins:
      - react
      - "@typescript-eslint"
      - prettier

      # Extra awesome ESLint rules
      - unicorn

      # It is necessary to turn warnings into errors to be caught by the Git hooks
      - only-error

      # Rules for jest-dom
      - jest-dom

    rules:
      # ---------------------------------------------------------------------------
      # Project rules
      # ---------------------------------------------------------------------------

      # JavaScript: Limit 300 lines per file
      max-lines: 1

      # ---------------------------------------------------------------------------
      # Overwritten rules
      # ---------------------------------------------------------------------------

      # React: Allows use tsx files
      react/jsx-filename-extension:
        - error
        - extensions:
            - ".tsx"

      react/jsx-props-no-spreading: off

      # Import: Resolves TypeScript extensions
      import/extensions:
        - error
        - extensions:
            - ".ts"
            - ".tsx"

      # Import: Adds exception to tests
      import/no-extraneous-dependencies:
        - error
        - devDependencies:
            - "**/*.test.tsx"
            - "**/setupTests.ts"

      # Unicorn: Allows pascalCase for React components
      unicorn/filename-case:
        - error
        - cases:
            kebabCase: true
            pascalCase: true
            camelCase: true

      # React needs props abbreviation
      unicorn/prevent-abbreviations: off

    settings:
      # React: Detects React version
      react:
        version: detect

      # Import: Resolves JavaScript and TypeScript extensions
      import/resolver:
        node:
          extensions:
            - ".js"
            - ".ts"
            - ".tsx"
